apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: nodejs-app                                  # 6
        app.kubernetes.io/name: nodejs-app
    spec:
      containers:
        - image: girwar/nodejs-app:latest
          imagePullPolicy: IfNotPresent                         # 7
          name: nodejs-app
          ports:
            - containerPort: 80
